import Fuse from 'fuse.js';

export interface TradeInModel {
  name: string;
  category: string;
  brand: string;
}

// Comprehensive model list used for search across all pages
export const TRADE_IN_MODELS: TradeInModel[] = [
  // ── Phones ──────────────────────────────────────────────────────────────
  { name: "iPhone 15 Pro Max",      category: "Phone", brand: "Apple" },
  { name: "iPhone 15 Pro",          category: "Phone", brand: "Apple" },
  { name: "iPhone 15 Plus",         category: "Phone", brand: "Apple" },
  { name: "iPhone 15",              category: "Phone", brand: "Apple" },
  { name: "iPhone 14 Pro Max",      category: "Phone", brand: "Apple" },
  { name: "iPhone 14 Pro",          category: "Phone", brand: "Apple" },
  { name: "iPhone 14 Plus",         category: "Phone", brand: "Apple" },
  { name: "iPhone 14",              category: "Phone", brand: "Apple" },
  { name: "iPhone 13 Pro Max",      category: "Phone", brand: "Apple" },
  { name: "iPhone 13 Pro",          category: "Phone", brand: "Apple" },
  { name: "iPhone 13",              category: "Phone", brand: "Apple" },
  { name: "iPhone 12 Pro Max",      category: "Phone", brand: "Apple" },
  { name: "iPhone 12 Pro",          category: "Phone", brand: "Apple" },
  { name: "iPhone 12",              category: "Phone", brand: "Apple" },
  { name: "iPhone 11 Pro Max",      category: "Phone", brand: "Apple" },
  { name: "iPhone 11 Pro",          category: "Phone", brand: "Apple" },
  { name: "iPhone 11",              category: "Phone", brand: "Apple" },
  { name: "Galaxy S24 Ultra",       category: "Phone", brand: "Samsung" },
  { name: "Galaxy S24+",            category: "Phone", brand: "Samsung" },
  { name: "Galaxy S24",             category: "Phone", brand: "Samsung" },
  { name: "Galaxy S23 Ultra",       category: "Phone", brand: "Samsung" },
  { name: "Galaxy S23+",            category: "Phone", brand: "Samsung" },
  { name: "Galaxy S23",             category: "Phone", brand: "Samsung" },
  { name: "Galaxy S22 Ultra",       category: "Phone", brand: "Samsung" },
  { name: "Galaxy S22+",            category: "Phone", brand: "Samsung" },
  { name: "Galaxy S22",             category: "Phone", brand: "Samsung" },
  { name: "Galaxy S21 Ultra",       category: "Phone", brand: "Samsung" },
  { name: "Galaxy S21+",            category: "Phone", brand: "Samsung" },
  { name: "Galaxy S21",             category: "Phone", brand: "Samsung" },
  { name: "Galaxy A54",             category: "Phone", brand: "Samsung" },
  { name: "Galaxy A34",             category: "Phone", brand: "Samsung" },
  { name: "Galaxy Z Fold 5",        category: "Phone", brand: "Samsung" },
  { name: "Galaxy Z Flip 5",        category: "Phone", brand: "Samsung" },
  { name: "Pixel 8 Pro",            category: "Phone", brand: "Google" },
  { name: "Pixel 8",                category: "Phone", brand: "Google" },
  { name: "Pixel 7 Pro",            category: "Phone", brand: "Google" },
  { name: "Pixel 7",                category: "Phone", brand: "Google" },
  { name: "Pixel 6 Pro",            category: "Phone", brand: "Google" },
  { name: "Pixel 6",                category: "Phone", brand: "Google" },
  { name: "OnePlus 12",             category: "Phone", brand: "OnePlus" },
  { name: "OnePlus 11",             category: "Phone", brand: "OnePlus" },
  { name: "OnePlus 10 Pro",         category: "Phone", brand: "OnePlus" },
  { name: "Nothing Phone (2)",      category: "Phone", brand: "Nothing" },
  { name: "Nothing Phone (1)",      category: "Phone", brand: "Nothing" },
  { name: "Edge 50 Pro",            category: "Phone", brand: "Motorola" },
  { name: "Edge 40 Pro",            category: "Phone", brand: "Motorola" },
  { name: "Moto G84",               category: "Phone", brand: "Motorola" },
  { name: "Redmi Note 13 Pro",      category: "Phone", brand: "Xiaomi" },
  { name: "Redmi Note 13",          category: "Phone", brand: "Xiaomi" },
  { name: "Redmi Note 12",          category: "Phone", brand: "Xiaomi" },
  { name: "Redmi Note 11 Pro",      category: "Phone", brand: "Xiaomi" },
  { name: "Redmi Note 10 Pro",      category: "Phone", brand: "Xiaomi" },
  { name: "Redmi Note 10 5G",       category: "Phone", brand: "Xiaomi" },
  { name: "Redmi Note 9S",          category: "Phone", brand: "Xiaomi" },
  { name: "Xiaomi 13 Pro",          category: "Phone", brand: "Xiaomi" },
  { name: "Xiaomi 13",              category: "Phone", brand: "Xiaomi" },
  { name: "P60 Pro",                category: "Phone", brand: "Huawei" },
  { name: "P50 Pro",                category: "Phone", brand: "Huawei" },
  { name: "Mate 50 Pro",            category: "Phone", brand: "Huawei" },
  { name: "Nokia G60 5G",           category: "Phone", brand: "Nokia" },
  { name: "Nokia XR21",             category: "Phone", brand: "Nokia" },
  { name: "Xperia 1 V",             category: "Phone", brand: "Sony" },
  { name: "Xperia 5 V",             category: "Phone", brand: "Sony" },
  { name: "Xperia 10 V",            category: "Phone", brand: "Sony" },
  { name: "Find X6 Pro",            category: "Phone", brand: "Oppo" },
  { name: "Reno 10 Pro",            category: "Phone", brand: "Oppo" },
  { name: "Magic5 Pro",             category: "Phone", brand: "Honor" },
  { name: "Fairphone 5",            category: "Phone", brand: "Fairphone" },
  { name: "Fairphone 4",            category: "Phone", brand: "Fairphone" },
  // ── Laptops ─────────────────────────────────────────────────────────────
  { name: 'MacBook Pro 16" M3 Max', category: "Laptop", brand: "Apple" },
  { name: 'MacBook Pro 16" M3 Pro', category: "Laptop", brand: "Apple" },
  { name: 'MacBook Pro 14" M3 Max', category: "Laptop", brand: "Apple" },
  { name: 'MacBook Pro 14" M3 Pro', category: "Laptop", brand: "Apple" },
  { name: 'MacBook Air 15" M3',     category: "Laptop", brand: "Apple" },
  { name: 'MacBook Air 13" M3',     category: "Laptop", brand: "Apple" },
  { name: 'MacBook Air 15" M2',     category: "Laptop", brand: "Apple" },
  { name: 'MacBook Air 13" M2',     category: "Laptop", brand: "Apple" },
  { name: 'MacBook Air 13" M1',     category: "Laptop", brand: "Apple" },
  { name: "XPS 15 (2024)",          category: "Laptop", brand: "Dell" },
  { name: "XPS 13 (2024)",          category: "Laptop", brand: "Dell" },
  { name: "Inspiron 15",            category: "Laptop", brand: "Dell" },
  { name: "ThinkPad X1 Carbon Gen 12", category: "Laptop", brand: "Lenovo" },
  { name: "ThinkPad T14s Gen 5",    category: "Laptop", brand: "Lenovo" },
  { name: "IdeaPad Slim 5",         category: "Laptop", brand: "Lenovo" },
  { name: "Legion 5i Gen 9",        category: "Laptop", brand: "Lenovo" },
  { name: "Spectre x360 14",        category: "Laptop", brand: "HP" },
  { name: "EliteBook 840 G11",      category: "Laptop", brand: "HP" },
  { name: "Pavilion 15",            category: "Laptop", brand: "HP" },
  { name: "ZenBook 14 OLED",        category: "Laptop", brand: "ASUS" },
  { name: "ROG Zephyrus G14 2024",  category: "Laptop", brand: "ASUS" },
  { name: "Surface Pro 11",         category: "Laptop", brand: "Microsoft" },
  { name: "Surface Pro 10",         category: "Laptop", brand: "Microsoft" },
  { name: "Surface Laptop 5",       category: "Laptop", brand: "Microsoft" },
  // ── Consoles ────────────────────────────────────────────────────────────
  { name: "PS5 Disc Edition",       category: "Console", brand: "Sony PlayStation" },
  { name: "PS5 Digital Edition",    category: "Console", brand: "Sony PlayStation" },
  { name: "PS4 Pro",                category: "Console", brand: "Sony PlayStation" },
  { name: "PS4 Slim",               category: "Console", brand: "Sony PlayStation" },
  { name: "PS4",                    category: "Console", brand: "Sony PlayStation" },
  { name: "PS3 Slim",               category: "Console", brand: "Sony PlayStation" },
  { name: "PS3",                    category: "Console", brand: "Sony PlayStation" },
  { name: "Xbox Series X",          category: "Console", brand: "Microsoft Xbox" },
  { name: "Xbox Series S",          category: "Console", brand: "Microsoft Xbox" },
  { name: "Xbox One X",             category: "Console", brand: "Microsoft Xbox" },
  { name: "Xbox One S",             category: "Console", brand: "Microsoft Xbox" },
  { name: "Xbox One",               category: "Console", brand: "Microsoft Xbox" },
  { name: "Xbox 360 S",             category: "Console", brand: "Microsoft Xbox" },
  { name: "Xbox 360",               category: "Console", brand: "Microsoft Xbox" },
  { name: "Nintendo Switch OLED",   category: "Console", brand: "Nintendo" },
  { name: "Nintendo Switch (V2)",   category: "Console", brand: "Nintendo" },
  { name: "Nintendo Switch Lite",   category: "Console", brand: "Nintendo" },
  // ── Tablets ─────────────────────────────────────────────────────────────
  { name: 'iPad Pro 13" M4',        category: "Tablet", brand: "Apple" },
  { name: 'iPad Pro 11" M4',        category: "Tablet", brand: "Apple" },
  { name: 'iPad Air 13" M2',        category: "Tablet", brand: "Apple" },
  { name: 'iPad Air 11" M2',        category: "Tablet", brand: "Apple" },
  { name: "iPad mini 7th Gen",      category: "Tablet", brand: "Apple" },
  { name: 'iPad Pro 13" M2',        category: "Tablet", brand: "Apple" },
  { name: 'iPad Pro 11" M2',        category: "Tablet", brand: "Apple" },
  { name: "iPad Air 5th Gen",       category: "Tablet", brand: "Apple" },
  { name: "iPad 10th Gen",          category: "Tablet", brand: "Apple" },
  { name: "iPad 9th Gen",           category: "Tablet", brand: "Apple" },
  { name: "Galaxy Tab S10 Ultra",   category: "Tablet", brand: "Samsung" },
  { name: "Galaxy Tab S10+",        category: "Tablet", brand: "Samsung" },
  { name: "Galaxy Tab S10",         category: "Tablet", brand: "Samsung" },
  { name: "Galaxy Tab S9 Ultra",    category: "Tablet", brand: "Samsung" },
  { name: "Galaxy Tab S9+",         category: "Tablet", brand: "Samsung" },
  { name: "Galaxy Tab S9",          category: "Tablet", brand: "Samsung" },
  // ── Smartwatches ────────────────────────────────────────────────────────
  { name: "Apple Watch Ultra 2",    category: "Smartwatch", brand: "Apple" },
  { name: "Apple Watch Series 9",   category: "Smartwatch", brand: "Apple" },
  { name: "Apple Watch Series 8",   category: "Smartwatch", brand: "Apple" },
  { name: "Apple Watch SE 2nd Gen", category: "Smartwatch", brand: "Apple" },
  { name: "Galaxy Watch 6 Classic", category: "Smartwatch", brand: "Samsung" },
  { name: "Galaxy Watch 6",         category: "Smartwatch", brand: "Samsung" },
  { name: "Galaxy Watch 5 Pro",     category: "Smartwatch", brand: "Samsung" },
  { name: "Fitbit Sense 2",         category: "Smartwatch", brand: "Fitbit" },
  { name: "Fitbit Versa 4",         category: "Smartwatch", brand: "Fitbit" },
  // ── Audio ────────────────────────────────────────────────────────────────
  { name: "AirPods Max",            category: "Audio", brand: "Apple" },
  { name: "AirPods Pro 2",          category: "Audio", brand: "Apple" },
  { name: "AirPods Pro",            category: "Audio", brand: "Apple" },
  { name: "AirPods 3rd Gen",        category: "Audio", brand: "Apple" },
  { name: "WH-1000XM5",             category: "Audio", brand: "Sony" },
  { name: "WF-1000XM5",             category: "Audio", brand: "Sony" },
  { name: "WH-1000XM4",             category: "Audio", brand: "Sony" },
  { name: "QuietComfort Ultra",     category: "Audio", brand: "Bose" },
  { name: "QuietComfort Earbuds II",category: "Audio", brand: "Bose" },
];

export const TRADE_IN_MODELS_FUSE = new Fuse(TRADE_IN_MODELS, {
  keys: [
    { name: 'name',     weight: 0.7 },  // model name (primary)
    { name: 'brand',    weight: 0.25 }, // brand — "samsung" matches Galaxy models
    { name: 'category', weight: 0.05 }, // category — "phone" / "laptop" shows results
  ],
  threshold: 0.4,
  ignoreLocation: true,
});
