import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const connectionString = process.env.DATABASE_URL ?? 'postgresql://ai_ecommerce:ai_ecommerce@localhost:5432/ai_ecommerce?schema=public';
const pool    = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma  = new PrismaClient({ adapter } as any);

const DEVICES = [
    // Phones — Apple
    { name: "iPhone 15 Pro Max",       brand: "Apple",           category: "Phone" },
    { name: "iPhone 15 Pro",           brand: "Apple",           category: "Phone" },
    { name: "iPhone 15 Plus",          brand: "Apple",           category: "Phone" },
    { name: "iPhone 15",               brand: "Apple",           category: "Phone" },
    { name: "iPhone 14 Pro Max",       brand: "Apple",           category: "Phone" },
    { name: "iPhone 14 Pro",           brand: "Apple",           category: "Phone" },
    { name: "iPhone 14 Plus",          brand: "Apple",           category: "Phone" },
    { name: "iPhone 14",               brand: "Apple",           category: "Phone" },
    { name: "iPhone 13 Pro Max",       brand: "Apple",           category: "Phone" },
    { name: "iPhone 13 Pro",           brand: "Apple",           category: "Phone" },
    { name: "iPhone 13",               brand: "Apple",           category: "Phone" },
    { name: "iPhone 12 Pro Max",       brand: "Apple",           category: "Phone" },
    { name: "iPhone 12 Pro",           brand: "Apple",           category: "Phone" },
    { name: "iPhone 12",               brand: "Apple",           category: "Phone" },
    { name: "iPhone 11 Pro Max",       brand: "Apple",           category: "Phone" },
    { name: "iPhone 11 Pro",           brand: "Apple",           category: "Phone" },
    { name: "iPhone 11",               brand: "Apple",           category: "Phone" },
    { name: "Galaxy S24 Ultra",        brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S24+",             brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S24",              brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S23 Ultra",        brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S23+",             brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S23",              brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S22 Ultra",        brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S22+",             brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S22",              brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S21 Ultra",        brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S21+",             brand: "Samsung",         category: "Phone" },
    { name: "Galaxy S21",              brand: "Samsung",         category: "Phone" },
    { name: "Galaxy A54",              brand: "Samsung",         category: "Phone" },
    { name: "Galaxy A34",              brand: "Samsung",         category: "Phone" },
    { name: "Galaxy Z Fold 5",         brand: "Samsung",         category: "Phone" },
    { name: "Galaxy Z Flip 5",         brand: "Samsung",         category: "Phone" },
    { name: "Pixel 8 Pro",             brand: "Google",          category: "Phone" },
    { name: "Pixel 8",                 brand: "Google",          category: "Phone" },
    { name: "Pixel 7 Pro",             brand: "Google",          category: "Phone" },
    { name: "Pixel 7",                 brand: "Google",          category: "Phone" },
    { name: "Pixel 6 Pro",             brand: "Google",          category: "Phone" },
    { name: "Pixel 6",                 brand: "Google",          category: "Phone" },
    { name: "OnePlus 12",              brand: "OnePlus",         category: "Phone" },
    { name: "OnePlus 11",              brand: "OnePlus",         category: "Phone" },
    { name: "OnePlus 10 Pro",          brand: "OnePlus",         category: "Phone" },
    { name: "Nothing Phone (2)",       brand: "Nothing",         category: "Phone" },
    { name: "Nothing Phone (1)",       brand: "Nothing",         category: "Phone" },
    { name: "Edge 50 Pro",             brand: "Motorola",        category: "Phone" },
    { name: "Edge 40 Pro",             brand: "Motorola",        category: "Phone" },
    { name: "Moto G84",                brand: "Motorola",        category: "Phone" },
    { name: "Redmi Note 13 Pro",       brand: "Xiaomi",          category: "Phone" },
    { name: "Redmi Note 13",           brand: "Xiaomi",          category: "Phone" },
    { name: "Redmi Note 12",           brand: "Xiaomi",          category: "Phone" },
    { name: "Redmi Note 11 Pro",       brand: "Xiaomi",          category: "Phone" },
    { name: "Redmi Note 10 Pro",       brand: "Xiaomi",          category: "Phone" },
    { name: "Redmi Note 10 5G",        brand: "Xiaomi",          category: "Phone" },
    { name: "Redmi Note 9S",           brand: "Xiaomi",          category: "Phone" },
    { name: "Xiaomi 13 Pro",           brand: "Xiaomi",          category: "Phone" },
    { name: "Xiaomi 13",               brand: "Xiaomi",          category: "Phone" },
    { name: "P60 Pro",                 brand: "Huawei",          category: "Phone" },
    { name: "P50 Pro",                 brand: "Huawei",          category: "Phone" },
    { name: "Mate 50 Pro",             brand: "Huawei",          category: "Phone" },
    { name: "Nokia G60 5G",            brand: "Nokia",           category: "Phone" },
    { name: "Nokia XR21",              brand: "Nokia",           category: "Phone" },
    { name: "Xperia 1 V",              brand: "Sony",            category: "Phone" },
    { name: "Xperia 5 V",              brand: "Sony",            category: "Phone" },
    { name: "Xperia 10 V",             brand: "Sony",            category: "Phone" },
    { name: "Find X6 Pro",             brand: "Oppo",            category: "Phone" },
    { name: "Reno 10 Pro",             brand: "Oppo",            category: "Phone" },
    { name: "Magic5 Pro",              brand: "Honor",           category: "Phone" },
    { name: "Fairphone 5",             brand: "Fairphone",       category: "Phone" },
    { name: "Fairphone 4",             brand: "Fairphone",       category: "Phone" },
    // Laptops
    { name: "MacBook Pro 16 M3 Max",   brand: "Apple",           category: "Laptop" },
    { name: "MacBook Pro 16 M3 Pro",   brand: "Apple",           category: "Laptop" },
    { name: "MacBook Pro 14 M3 Max",   brand: "Apple",           category: "Laptop" },
    { name: "MacBook Pro 14 M3 Pro",   brand: "Apple",           category: "Laptop" },
    { name: "MacBook Air 15 M3",       brand: "Apple",           category: "Laptop" },
    { name: "MacBook Air 13 M3",       brand: "Apple",           category: "Laptop" },
    { name: "MacBook Air 15 M2",       brand: "Apple",           category: "Laptop" },
    { name: "MacBook Air 13 M2",       brand: "Apple",           category: "Laptop" },
    { name: "MacBook Air 13 M1",       brand: "Apple",           category: "Laptop" },
    { name: "XPS 15 (2024)",           brand: "Dell",            category: "Laptop" },
    { name: "XPS 13 (2024)",           brand: "Dell",            category: "Laptop" },
    { name: "Inspiron 15",             brand: "Dell",            category: "Laptop" },
    { name: "ThinkPad X1 Carbon Gen 12", brand: "Lenovo",        category: "Laptop" },
    { name: "ThinkPad T14s Gen 5",     brand: "Lenovo",          category: "Laptop" },
    { name: "IdeaPad Slim 5",          brand: "Lenovo",          category: "Laptop" },
    { name: "Legion 5i Gen 9",         brand: "Lenovo",          category: "Laptop" },
    { name: "Spectre x360 14",         brand: "HP",              category: "Laptop" },
    { name: "EliteBook 840 G11",       brand: "HP",              category: "Laptop" },
    { name: "Pavilion 15",             brand: "HP",              category: "Laptop" },
    { name: "ZenBook 14 OLED",         brand: "ASUS",            category: "Laptop" },
    { name: "ROG Zephyrus G14 2024",   brand: "ASUS",            category: "Laptop" },
    { name: "Surface Pro 11",          brand: "Microsoft",       category: "Laptop" },
    { name: "Surface Pro 10",          brand: "Microsoft",       category: "Laptop" },
    { name: "Surface Laptop 5",        brand: "Microsoft",       category: "Laptop" },
    // Consoles
    { name: "PS5 Disc Edition",        brand: "Sony PlayStation", category: "Console" },
    { name: "PS5 Digital Edition",     brand: "Sony PlayStation", category: "Console" },
    { name: "PS4 Pro",                 brand: "Sony PlayStation", category: "Console" },
    { name: "PS4 Slim",                brand: "Sony PlayStation", category: "Console" },
    { name: "PS4",                     brand: "Sony PlayStation", category: "Console" },
    { name: "Xbox Series X",           brand: "Microsoft Xbox",  category: "Console" },
    { name: "Xbox Series S",           brand: "Microsoft Xbox",  category: "Console" },
    { name: "Xbox One X",              brand: "Microsoft Xbox",  category: "Console" },
    { name: "Xbox One S",              brand: "Microsoft Xbox",  category: "Console" },
    { name: "Nintendo Switch OLED",    brand: "Nintendo",        category: "Console" },
    { name: "Nintendo Switch V2",      brand: "Nintendo",        category: "Console" },
    { name: "Nintendo Switch Lite",    brand: "Nintendo",        category: "Console" },
    // Tablets
    { name: "iPad Pro 13 M4",          brand: "Apple",           category: "Tablet" },
    { name: "iPad Pro 11 M4",          brand: "Apple",           category: "Tablet" },
    { name: "iPad Air 13 M2",          brand: "Apple",           category: "Tablet" },
    { name: "iPad Air 11 M2",          brand: "Apple",           category: "Tablet" },
    { name: "iPad mini 7th Gen",       brand: "Apple",           category: "Tablet" },
    { name: "iPad Pro 13 M2",          brand: "Apple",           category: "Tablet" },
    { name: "iPad Pro 11 M2",          brand: "Apple",           category: "Tablet" },
    { name: "iPad Air 5th Gen",        brand: "Apple",           category: "Tablet" },
    { name: "iPad 10th Gen",           brand: "Apple",           category: "Tablet" },
    { name: "iPad 9th Gen",            brand: "Apple",           category: "Tablet" },
    { name: "Galaxy Tab S10 Ultra",    brand: "Samsung",         category: "Tablet" },
    { name: "Galaxy Tab S10+",         brand: "Samsung",         category: "Tablet" },
    { name: "Galaxy Tab S10",          brand: "Samsung",         category: "Tablet" },
    { name: "Galaxy Tab S9 Ultra",     brand: "Samsung",         category: "Tablet" },
    { name: "Galaxy Tab S9+",          brand: "Samsung",         category: "Tablet" },
    { name: "Galaxy Tab S9",           brand: "Samsung",         category: "Tablet" },
    // Smartwatches
    { name: "Apple Watch Ultra 2",     brand: "Apple",           category: "Smartwatch" },
    { name: "Apple Watch Series 9",    brand: "Apple",           category: "Smartwatch" },
    { name: "Apple Watch Series 8",    brand: "Apple",           category: "Smartwatch" },
    { name: "Apple Watch SE 2nd Gen",  brand: "Apple",           category: "Smartwatch" },
    { name: "Galaxy Watch 6 Classic",  brand: "Samsung",         category: "Smartwatch" },
    { name: "Galaxy Watch 6",          brand: "Samsung",         category: "Smartwatch" },
    { name: "Galaxy Watch 5 Pro",      brand: "Samsung",         category: "Smartwatch" },
    { name: "Fitbit Sense 2",          brand: "Fitbit",          category: "Smartwatch" },
    { name: "Fitbit Versa 4",          brand: "Fitbit",          category: "Smartwatch" },
    // Audio
    { name: "AirPods Max",             brand: "Apple",           category: "Audio" },
    { name: "AirPods Pro 2",           brand: "Apple",           category: "Audio" },
    { name: "AirPods Pro",             brand: "Apple",           category: "Audio" },
    { name: "AirPods 3rd Gen",         brand: "Apple",           category: "Audio" },
    { name: "WH-1000XM5",              brand: "Sony",            category: "Audio" },
    { name: "WF-1000XM5",              brand: "Sony",            category: "Audio" },
    { name: "WH-1000XM4",              brand: "Sony",            category: "Audio" },
    { name: "QuietComfort Ultra",      brand: "Bose",            category: "Audio" },
    { name: "QuietComfort Earbuds II", brand: "Bose",            category: "Audio" },
];

async function main() {
    let created = 0;
    for (const d of DEVICES) {
        await prisma.tradeInDevice.upsert({
            where:  { brand_name: { brand: d.brand, name: d.name } },
            update: {},
            create: { ...d, isActive: true },
        });
        created++;
    }
    console.log(`✓ Seeded ${created} trade-in search devices`);
}

main()
    .catch(e => { console.error(e.message); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); await pool.end(); });
